#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Output\StreamOutput;
use balance\commands\WorkerCommand;
use balance\commands\ClientCommand;
use balance\Conf;

$application = new Application();
$application->setName('Balance microservice');
$application->add(new WorkerCommand);
$application->add(new ClientCommand);
$application->run();
