version: "3.2"
services:

  phpclient:
    build:
      context: .
      dockerfile: /docker/php/Dockerfile
    command: ./balance client -vvv
    depends_on:
      - gearman
      - mysql

  phpworker:
    build:
      context: .
      dockerfile: /docker/php/Dockerfile
    depends_on:
      - gearman
      - mysql
      - phpclient

  gearman:
    image: artefactual/gearmand:1.1.17-alpine
    logging:
      driver: "none"
    ports:
      - "3000:4730"
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:5.7.21
    ports:
      - "4000:3306"
    volumes:
      - ./db/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    logging:
      driver: "none"
    environment:
      MYSQL_ROOT_PASSWORD: 123
    restart: always
